-- Transferencia saneada: se omitió la limpieza histórica de dos contactos reales.
-- No contiene DDL necesario para compilar o desplegar el panel.
-- Intencionalmente sin operaciones ni datos personales.
