import { act, cleanup, renderHook } from '@testing-library/react'
import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import type { SseEvent } from '../useRealTime'
const mocks = vi.hoisted(() => ({ fetch: vi.fn(), notify: vi.fn(), update: (_event: SseEvent) => {} }))
vi.mock('@/lib/fetchJson', () => ({ fetchJson: mocks.fetch }))
vi.mock('../useRealTime', () => ({ useRealTime: (update: (event: SseEvent) => void) => { mocks.update = update; return 'connected' } }))
vi.mock('../useDesktopNotifications', () => ({ useDesktopNotifications: () => ({ permission: 'default', request: vi.fn(), notify: mocks.notify }) }))
import { useConversations } from '../useConversations'

beforeEach(() => { vi.useFakeTimers(); mocks.fetch.mockResolvedValue({ conversations: [], total: 0, messages: [] }) })
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); vi.clearAllMocks() })
it('coalesces bursts of delivery events into one refresh and cancels queued work on unmount', async () => {
  vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
  const { unmount } = renderHook(useConversations)
  await act(async () => {})
  mocks.fetch.mockClear()
  act(() => { for (let i = 0; i < 20; i++) mocks.update({ type: 'update', source: 'delivery' }) })
  await act(async () => { await vi.advanceTimersByTimeAsync(150) })
  expect(mocks.fetch).toHaveBeenCalledTimes(1)
  act(() => mocks.update({ type: 'update' }))
  unmount()
  await vi.advanceTimersByTimeAsync(150)
  expect(mocks.fetch).toHaveBeenCalledTimes(1)
})
it('pauses hidden-tab polling but keeps notifications and refreshes the active chat on return', async () => {
  const hidden = vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
  const { result } = renderHook(useConversations)
  await act(async () => { result.current.openConv('test-phone') })
  mocks.fetch.mockClear(); hidden.mockReturnValue(true)
  await act(async () => { await vi.advanceTimersByTimeAsync(45_000) })
  act(() => mocks.update({ type: 'update', source: 'message' }))
  expect(mocks.fetch).not.toHaveBeenCalled()
  expect(mocks.notify).toHaveBeenCalledOnce()
  hidden.mockReturnValue(false)
  await act(async () => { document.dispatchEvent(new Event('visibilitychange')) })
  expect(mocks.fetch.mock.calls.map(([url]) => url)).toEqual(['/api/conversations', '/api/conversations?phone=test-phone'])
})

it('keeps at most one slow inbox read and one follow-up, including events arriving during the read', async () => {
  vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
  let finish!: (value: unknown) => void
  mocks.fetch.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
  const { result } = renderHook(useConversations)
  act(() => { for (let i = 0; i < 20; i++) result.current.refreshConversations() })
  await act(async () => { await vi.advanceTimersByTimeAsync(15_000) })
  expect(mocks.fetch).toHaveBeenCalledTimes(1)
  await act(async () => finish({ conversations: [], total: 0 }))
  expect(mocks.fetch).toHaveBeenCalledTimes(2)
  expect(result.current.loading).toBe(false)
})

it('does not interrupt pagination with background refreshes and retains the loaded page', async () => {
  vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
  const conv = (n: number) => ({ phone_number: String(n), last_at: '2026-10-01', last_message: '' })
  const first = Array.from({length: 200}, (_, n) => conv(n))
  mocks.fetch.mockResolvedValueOnce({ conversations: first, total: 201 })
  const { result } = renderHook(useConversations)
  await act(async () => {})
  let finish!: (value: unknown) => void
  mocks.fetch.mockImplementationOnce(() => new Promise(resolve => { finish = resolve }))
  act(() => result.current.loadMoreConvs())
  act(() => { result.current.refreshConversations(); result.current.refreshConversations() })
  expect(mocks.fetch).toHaveBeenCalledTimes(2)
  mocks.fetch.mockImplementation((url: string) => Promise.resolve({ conversations: url.includes('offset=200') ? [conv(200)] : first, total: 201 }))
  await act(async () => finish({ conversations: [conv(200)], total: 201 }))
  expect(result.current.convs).toHaveLength(201)
  expect(result.current.hasMore).toBe(false)
})

it('coalesces message polls, aborts obsolete reads, and rejects a late response when revisiting the same chat', async () => {
  vi.spyOn(document, 'hidden', 'get').mockReturnValue(false)
  const reads: { resolve: (value: unknown) => void; signal: AbortSignal }[] = []
  mocks.fetch.mockImplementation((url: string, init: RequestInit) => url.includes('phone=')
    ? new Promise(resolve => reads.push({ resolve, signal: init.signal as AbortSignal }))
    : Promise.resolve({ conversations: [], total: 0 }))
  const { result, unmount } = renderHook(useConversations)
  act(() => result.current.openConv('a'))
  await act(async () => { await vi.advanceTimersByTimeAsync(9_000) })
  expect(reads).toHaveLength(1)
  act(() => { result.current.openConv('b'); result.current.openConv('a') })
  expect(reads).toHaveLength(3)
  expect(reads[0].signal.aborted).toBe(true)
  expect(reads[1].signal.aborted).toBe(true)
  await act(async () => reads[2].resolve({ messages: [{ id: 'fresh' }] }))
  await act(async () => reads[0].resolve({ messages: [{ id: 'stale' }] }))
  expect(result.current.messages[0].id).toBe('fresh')
  act(() => result.current.openConv('c'))
  unmount()
  expect(reads[3].signal.aborted).toBe(true)
})
